name: build adocs develop

on:
  push:
    branches:
    - develop
    paths:
    - docs/**

jobs:
  adoc_build:
    runs-on: ubuntu-18.04
    name: asciidoctor build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build html
      id: adocbuild
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor -D build -R docs 'docs/**/*.adoc'"
    - name: copy index.html
      uses: canastro/copy-file-action@master
      with:
        source: "docs/index.html"
        target: "build/index.html"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
