name: build adocs and publish main v1.0 to production

on:
  push:
    branches:
      - main
    paths:
      - docs/1.0/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: asciidoctor build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Build html nlod 1.0 no
        id: adocbuild_n0
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -D docs/1.0/no -o index.html -a lang=nb docs/1.0/no/index.adoc"

      - name: Build html nlod 1.0 en
        id: adocbuild_en
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -D docs/1.0/en -o index.html -a lang=en docs/1.0/en/index.adoc"

      - name: Upload html nlod 1.0 to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
        id: upload-nlod
        with:
          ontology-type: "licence"
          ontology: "nlod"
          version: "1.0"
          host: "https://fellesdatakatalog.digdir.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
          files: |
            docs/1.0/no/index.html text/html nb
            docs/1.0/en/index.html text/html en
